language: objective-c
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Notificationz.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Notificationz-ios"
  - OSX_FRAMEWORK_SCHEME="Notificationz-osx"
  - TVOS_FRAMEWORK_SCHEME="Notificationz-tvos"
  - WATCHOS_FRAMEWORK_SCHEME="Notificationz-watchos"
  - IOS_SDK=iphonesimulator11.0
  - OSX_SDK=macosx10.13
  - TVOS_SDK=appletvsimulator11.0
  - WATCHOS_SDK=watchsimulator4.0
  matrix:
  - DESTINATION="OS=10.1,name=iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.0,name=iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="NO"
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- if [ $RUN_TESTS == "YES" ]; then xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME"
  -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  test | xcpretty -c; else xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk
  "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build
  | xcpretty -c; fi
notifications:
  email: false
  slack:
    secure: L4JLPCgd5f0WOjD5yO9gwZuIg+bnCySwZHbdVUnP5DmolS+bF25aHNqFoYaR649+h2o/HHy5vPNZUb8VnC7tii8fNgXs3csmggEe+oANSZkS7486LeeqVoz/KMOtM/G/6R8mZAdtfwocaqAYghDSememLMfuaWsWoXtqtIJoHmtfe1DcmU1+Qld5Ylv2+sS9bAErd0tV0iwzt0R5QbZQDer7GtAZzHqMDMP3fcueNGj59jBdUp7dXgH05DilpLUWz8/1VjyFHrwqeLMiGwqAkybjIkSn92/oqIp54C9yu/6BrqPsLjBigfD7VYidypU9AFGONwva71jVHDY7avEiWpNcsvZ9UIKoUoeGSS/OZupsqqYIaYwa6kN/a7dbjNp8i3w2jULCXNNZOuzlbwy9jF1SYuthvDCPRCvpqswjajlWUFrkj/DELKSsasGTqC4mw2+Z6zF9zIvpMp3pWoz+S3lQPqaeH2OLSX/nG6rAGImmNS7F3fjR3AZb/OSFJEJ9045Z58Xk3krbuCxV+Gwd6tbJ+xAdchh6Dlc376Ue+fsUd4ALO5R0AUpQ6liLUMu4ZZn9qmvVmQT2lkbxR8yB7fQoqAc10HpvuZVZ64aA3MGIgzq3772clo4fmCrDspPjkMnc5hxrkFjsnZxm4QFMHtAThCjfYHG1qrMs7XW5D+o=
